package:
  name: dappled
  version: "0.1.1"

source:
  path: ../
#  patches:
   # List any patch files here
   # - fix.patch

build:
  # noarch: python
  # noarch_python: True
  # preserve_egg_dir: True
  entry_points:
    - dappled = dappled.__main__:main
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyfiglet = pyfiglet:main
    #
    # Would create an entry point called pyfiglet that calls pyfiglet.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ruamel_yaml
    - appdirs
    - requests
    - conda-kapsel
    - netifaces

test:
  # Python imports
  imports:
    - dappled.command

  commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

    dappled --help
#    - pyfiglet --help

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: 
  license: 
  summary: 
  license_family: OTHER

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
