package:
  name: dappled
  version: "0.1.1"

source:
  path: ../

build:
  entry_points:
    - dappled = dappled.__main__:main

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - ruamel_yaml
    - appdirs
    - requests
    - conda-kapsel
    - netifaces

test:
  imports:
    - dappled.command

  commands:
    dappled --help

about:
  home: https://github.com/lhon/dappled
  license: Apache License v2.0
  summary: A tool for building and running deployable Jupyter notebooks
  license_family: Apache
